CREATE TABLE Users (
	uid VARCHAR(100) NOT NULL,
	password VARCHAR(50) NOT NULL,
	firstName VARCHAR(30) DEFAULT NULL,
	lastName VARCHAR(30) DEFAULT NULL,
	PRIMARY KEY (uid)
);

CREATE TABLE Categories (
	cid INT NOT NULL AUTO_INCREMENT,
	uid VARCHAR(100) NOT NULL,
	name VARCHAR(50) NOT NULL,
	PRIMARY KEY (cid),
	FOREIGN KEY (uid) REFERENCES Users(uid)
);

CREATE TABLE Quests (
	qid INT NOT NULL AUTO_INCREMENT,
	cid INT NOT NULL,
	name VARCHAR(100) NOT NULL,
	updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	urgency VARCHAR(20) DEFAULT NULL,
	dueDate TIMESTAMP NULL,
	timeLimit INT DEFAULT NULL,
	nqid INT DEFAULT NULL,
	cqid INT DEFAULT NULL,
	PRIMARY KEY (qid),
	FOREIGN KEY (cid) REFERENCES Categories(cid)
);